
 INSERT INTO listings (thumbnail_photo_url, image_2, image_3, users_id, brand, make, year, color, transmission, price, description)
VALUES
  ('https://www.outmotorsports.com/wp-content/uploads/2020/11/IMG_0004.jpg', 'https://di-uploads-pod25.dealerinspire.com/philhugheshonda/uploads/2020/08/honda-civic-interior.jpg', 'https://hooniverse.com/wp-content/uploads/2020/04/2020-honda-civic-si-front.jpg',  1, 'Honda', 'Civic', '2020', 'Red', 'Automatic', 25000, 'Experience the joy of driving in this 2020 Honda Civic. The vibrant red exterior is sure to turn heads, and the automatic transmission ensures a smooth and effortless ride. With only 25,000 miles, this car is in excellent condition and ready for your next adventure. Don''t miss out on this fantastic opportunity to own a stylish and reliable vehicle.'),
  ('https://i.ytimg.com/vi/eFWUQc-wDzI/maxresdefault.jpg', 'https://www.motortrend.com/uploads/2022/09/2024-Mustang-Interior-04.jpg', 'https://cdn.jdpower.com/JDP_2024%20Ford%20Mustang%20GT%20Black%20Rear%20Quarter%20View.jpg',  3, 'Ford', 'Mustang', '2022', 'Black', 'Automatic', 30000, 'Indulge in the power and style of the 2022 Ford Mustang GT. With its sleek black exterior, this brand-new car has never been used, offering you the opportunity to be its first proud owner. The automatic transmission ensures a powerful and exhilarating driving experience. With a price that reflects the value of a new Mustang, this is your chance to own a piece of automotive excellence.'),
  ('https://live.staticflickr.com/8664/27736897553_23535245f1_b.jpg', 'https://collectingcars.imgix.net/016166/DSC-2527.jpg?w=1263&fit=fillmax&crop=edges&auto=format,compress&cs=srgb&q=85', 'https://classiccarsandcampers.co.uk/storage/images/vehicle/1491/8892.jpg?v=1568384251', 2, 'VW', 'Beetle', '1985', 'Red', 'Manual', 70000, 'Step back in time with the iconic 1985 VW Beetle in a classic red. This manual transmission car is brand new and has never been used. With its timeless design and reliable manual transmission, this Beetle is a true collector gem.'),
  ('https://picolio.auto123.com/auto123-media/articles/2021/3/67984/audi_a3_2020fr.jpeg?scaledown=450', 'https://car-images.bauersecure.com/wp-images/3872/audi_a3_sportback_42.jpg', 'https://imgcdn.oto.com/large/gallery/interior/1/4/audi-a6-dashboard-view-530675.jpg', 2, 'Audi', 'A3', '2022', 'Blue', 'Automatic', 55000, 'Immerse yourself in luxury with the 2022 Audi A3. The elegant blue exterior and automatic transmission make this car a statement of style and performance. With its brand-new condition, this A3 is ready to deliver a premium driving experience.');

/* Featured listings*/

INSERT INTO listings (thumbnail_photo_url, image_2, image_3, users_id, brand, make, year, color, transmission, price, description, featured)
VALUES

  ('https://i.ytimg.com/vi/BraG882pXwU/maxresdefault.jpg', 'https://cars.usnews.com/static/images/Auto/custom/15080/2023_Toyota_Corolla_9.jpg', 'https://www.motortrend.com/uploads/sites/5/2020/04/2020-Toyota-Corolla-XSE-Hatchback-17.jpg',  2, 'Toyota', 'Corolla', '2018', 'Black', 'Manual', 18000, 'Rev up your driving experience with the featured 2018 Toyota Corolla. This well-maintained car comes with a detailed service history and a sleek black exterior. The manual transmission adds a touch of excitement to your daily commute.', true),
  ('https://toyotacanada.scene7.com/is/image/toyotacanada/2020_Toyota_Supra-1?ts=1688690336213&$Media-Large$&dpr=off', 'https://content.presspage.com/uploads/1523/1920_grsupra2019yellow-30-242946.jpg?10000', 'https://car-images.bauersecure.com/wp-images/3289/480x270/toyota_supra_164.jpg',  3, 'Toyota', 'Supra', '2019', 'Yellow', 'Automatic', 90000, 'Experience the thrill of the 2019 Toyota Supra. This yellow beauty comes with an automatic transmission and a well-documented service history. Do not miss out on the opportunity to own a piece of automotive history.', true),
  ('https://www.corvetteblogger.com/images/content/uploads/2021/07/072021_2.jpg', 'https://forums.corvetteactioncenter.com/media/1979-corvette-in-corvette-dark-green.17885/full', 'https://www.hobbycarcorvettes.net/wp-content/uploads/1979-black-corvette-oyster-interior-2022-65-1080x675.jpg',  1, 'Chevrolet', 'Corvette', '1979', 'Green', 'Manual', 80000, 'Own a piece of classic automotive history with the 1979 Chevrolet Corvette. This well-maintained, manual transmission car is a true gem. The green exterior adds a touch of vintage charm to this iconic Corvette.', true),
  ('https://images.squarespace-cdn.com/content/v1/58916f89bebafb5d2bed8684/1562782375640-VXX0LOE3WFNZSP098XUI/2005+Ford+GT+Red-1.jpg?format=2500w', 'https://images.drive.com.au/driveau/image/upload/c_fill,f_auto,g_auto,h_1080,q_auto:eco,w_1920/v1/cms/uploads/hPWmhtVS5yLSbKuYhCrB', 'https://journal.classiccars.com/media/2020/11/23126308-2005-ford-gt-std.jpg',  3, 'Ford', 'GT', '2005', 'Red', 'Manual', 80000, 'Step back in time with the 2005 Ford GT. This iconic red beauty with a manual transmission is in excellent condition, boasting a well-documented service history. Do not miss the chance to own a true collector piece.', true),
  ('https://i.gaw.to/content/photos/49/09/490953-nissan-frontier-2022-le-sens-du-timing.jpeg', 'https://img.hardworkingtrucks.com/files/base/randallreilly/all/image/2022/09/Frontier_back_.631930755ac10.png?auto=format%2Ccompress&fit=max&q=70&w=1200', 'https://o.aolcdn.com/images/dims3/GLOB/legacy_thumbnail/1062x597/format/jpg/quality/100/https://s.aolcdn.com/os/ab/_cms/2021/12/27144839/IMG_3961.jpg',  2, 'Nissan', 'Frontier', '2022', 'Green', 'Automatic', 60000, 'Explore the rugged terrain with the 2022 Nissan Frontier. This green automatic beauty is well-maintained with a detailed service history. Get ready for an adventurous journey with this reliable and stylish pickup truck.', true),
  ('https://www.freeway.com/knowledge-center/wp-content/uploads/sites/2/2023/01/what-happened-to-the-delorean-750x500.jpg', 'https://static.dezeen.com/uploads/2016/02/delorean-dmc-12-car_dezeen_1568.jpg',  'https://upload.wikimedia.org/wikipedia/commons/b/ba/1981_DeLorean_DMC-12_interior_Petersen.jpg',  1, 'DMC', 'Delorean', '1982', 'Silver', 'Manual', 18000, 'Mint condition Delorean. Diamond in the rough. Get this baby up to 88 miles per hour and it will take to places you have never seen. Only selling because my wife hates it.', true);





